In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [4]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500


In [ ]:
# Numpy

In [3]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1, 2, 3, 4, 5, 7, 12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]
         ])

In [23]:
n[0, 1] = 20

In [24]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[1] = [1, 1, 1]

In [29]:
n

array([[ 1, 20,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [30]:
n[:, 1]

array([20,  1,  8])

In [37]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [38]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [43]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [44]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
a + 1

array([1, 2, 3, 4, 5])

In [50]:
b = (10 + (a * 2)) ** 2 / 100

In [51]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [52]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [54]:
a

array([0, 1, 2, 3, 4])

In [53]:
a >= 2

array([False, False,  True,  True,  True])

In [55]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [56]:
a > b

array([False, False,  True,  True,  True])

In [57]:
a[a > b]

array([2, 3, 4])

In [60]:
a

array([0, 1, 2, 3, 4])

In [58]:
a.min()

np.int64(0)

In [59]:
a.max()

np.int64(4)

In [61]:
a.mean()

np.float64(2.0)

In [62]:
n.sum()

np.int64(51)

In [ ]:
# vectors

In [5]:
u = np.array([2, 3, 4, 5])

In [6]:
2 * u

array([ 4,  6,  8, 10])

In [7]:
v = np.array([1, 0, 0, 2])

In [8]:
u + v

array([3, 3, 4, 7])

In [9]:
u * v

array([ 2,  0,  0, 10])

In [ ]:
# multiplication

In [10]:
u.shape[0]

4

In [12]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [13]:
vector_vector_multiplication(u, v)

np.float64(12.0)

In [14]:
u.dot(v)

np.int64(12)

In [15]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [16]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [17]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [18]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [19]:
U.dot(v)

array([14,  5,  5])

In [20]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [24]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [25]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [26]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
# Identity matrix

In [28]:
I = np.eye(3)

In [30]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [29]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
# Matrix inverse

In [34]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [35]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [36]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])